# Generated by Django 5.0.7 on 2024-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('about', models.TextField(max_length=550)),
                ('degree', models.CharField(max_length=300)),
                ('school', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=300)),
                ('previous', models.TextField(max_length=550)),
                ('skills', models.TextField(max_length=550)),
            ],
        ),
    ]
